"""
Desktop-side exporter: bakes a fitted CompressedFractionalFilter's
constants into a small, ready-to-compile .c file for the plain-C
runtime (fracmemfilter.h / fracmemfilter.c, in embedded/c/).

A C project is normally built from several files together, so this
only generates the small file of *constants*. Ship fracmemfilter.h and
fracmemfilter.c alongside it once, unchanged, no matter how many
filters you export.

    fracmem.embedded.export_c(fitted_filter, "device_filter.c")
    # then compile device_filter.c + fracmemfilter.c into your project
"""
from pathlib import Path

from ..kernel import gl_weights

_C_DIR = Path(__file__).with_name("c")


def _fmt_c_array(values, ndigits: int = 8) -> str:
    return ", ".join(f"{float(v):.{ndigits}f}f" for v in values)


def generate_source_c(filt, w=None, instance_name: str = "filt") -> str:
    """filt: a fitted CompressedFractionalFilter. Returns the text of a
    small standalone .c file, meant to be compiled together with
    fracmemfilter.c (see embedded/c/)."""
    if filt.lam is None or filt.c is None:
        raise RuntimeError("filt must be fitted (call .fit(...)) before exporting")
    if filt.L > 64 or filt.p > 32:
        raise ValueError(
            f"L={filt.L}, p={filt.p} exceed fracmemMaxL=64 / fracmemMaxP=32 in "
            "fracmemfilter.h -- raise those constants and rebuild, or use smaller L/p."
        )
    if w is None:
        w = gl_weights(filt.alpha, filt.L)

    h_pow = filt.h ** (-filt.alpha)
    caputo = 1 if filt.definition == "caputo" else 0

    return (
        "/* Auto-generated by fracmem.embedded.export_c -- do not edit by hand.\n"
        f"   alpha={filt.alpha!r}  h={filt.h!r}  L={filt.L!r}  p={filt.p!r}  "
        f"definition={filt.definition!r}\n"
        "   Compile together with fracmemfilter.c (see embedded/c/). */\n"
        '#include "fracmemfilter.h"\n\n'
        f"static const float {instance_name}W[{filt.L}] = {{{_fmt_c_array(w[:filt.L])}}};\n"
        f"static const float {instance_name}Lam[{filt.p}] = {{{_fmt_c_array(filt.lam)}}};\n"
        f"static const float {instance_name}C[{filt.p}] = {{{_fmt_c_array(filt.c)}}};\n\n"
        f"FracmemFilter {instance_name};\n\n"
        f"void {instance_name}Setup(void)\n"
        "{\n"
        f"    fracmemInit(&{instance_name}, {filt.L}, {filt.p}, {h_pow:.8f}f, {caputo},\n"
        f"                {instance_name}W, {instance_name}Lam, {instance_name}C);\n"
        "}\n\n"
        f"/* call {instance_name}Setup() once at startup, then\n"
        f"   fracmemStep(&{instance_name}, x_k) -> derivative estimate, one sample at a time. */\n"
    )


def export_c(filt, path: str, w=None, instance_name: str = "filt"):
    """Write generate_source_c(...) straight to `path`."""
    Path(path).write_text(generate_source_c(filt, w=w, instance_name=instance_name))
